### ISSUE TITLE
Installation fails in CircleCI

### ISSUE THREAD

**Issue by grsabreu** [mhallin/graphql_ppx#11]
Thanks for the great package.
I'm tried to setup a CD in CircleCI and I'm always getting this:

```
Arguments: -c if [ ! -f ./ppx ]; then ln -s "$(opam config var graphql_ppx:bin)/graphql_ppx.native" ./ppx && chmod +x ppx; fi
Directory: /home/circleci/repo/node_modules/graphql_ppx
Output:
chmod: cannot operate on dangling symlink ‘ppx’
```

this is my .circleci.yml

```yml
version: 2
jobs:
  build:
    environment:
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      - TERM: xterm
    docker:
      - image: circleci/node:8.0
      - image: circleci/android:api-23-alpha

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install opam
          command: wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
      - run: opam switch 4.02.3
      - run:
          name: Install opam deps
          command: eval $(opam config env) && opam update && opam install -y jbuilder
      - run:
          name: Install node deps
          command: eval $(opam config env) && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      - run:
          command: |
            yarn android:release:generate

      - store_artifacts:
          path: android/app/build/outputs/apk/
          destination: android
      - store_artifacts:
          path: android/app/build/reports
          destination: android

```
